/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appointment: typeof import('./src/components/app/Appointment.vue')['default']
    AvailabilityAdd: typeof import('./src/components/admin/AvailabilityAdd.vue')['default']
    AvailabilityEdit: typeof import('./src/components/admin/AvailabilityEdit.vue')['default']
    AvailabilityList: typeof import('./src/components/admin/AvailabilityList.vue')['default']
    AvailabilityListSlot: typeof import('./src/components/admin/AvailabilityListSlot.vue')['default']
    AvailabilityListSlotsForDay: typeof import('./src/components/admin/AvailabilityListSlotsForDay.vue')['default']
    Button: typeof import('./src/components/_design-system/Button.vue')['default']
    Header: typeof import('./src/components/_design-system/Header.vue')['default']
    HeaderHexagons: typeof import('./src/components/_design-system/HeaderHexagons.vue')['default']
    Hexagon: typeof import('./src/components/_design-system/Hexagon.vue')['default']
    IconPractitioner: typeof import('./src/components/_design-system/IconPractitioner.vue')['default']
    Infos: typeof import('./src/components/app/Infos.vue')['default']
    InputDate: typeof import('./src/components/_design-system/InputDate.vue')['default']
    InputPhone: typeof import('./src/components/_design-system/InputPhone.vue')['default']
    Location: typeof import('./src/components/_design-system/Location.vue')['default']
    Login: typeof import('./src/components/admin/Login.vue')['default']
    Logout: typeof import('./src/components/admin/Logout.vue')['default']
    NextAppointment: typeof import('./src/components/app/NextAppointment.vue')['default']
    Osteopathy: typeof import('./src/components/app/Osteopathy.vue')['default']
    Phone: typeof import('./src/components/_design-system/Phone.vue')['default']
    PwaPrompt: typeof import('./src/components/admin/PwaPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionsList: typeof import('./src/components/admin/SessionsList.vue')['default']
    Timeline: typeof import('./src/components/app/Timeline.vue')['default']
  }
}
