export const PWA_SERVICE_WORKER_SCOPE = "/"
export const PWA_SERVICE_WORKER_SCRIPT_PATH = "/service-worker.js"
export const PWA_VAPID_PUBLIC_KEY_DEV = "BKcSy-jXVsGB1hYYB7RJq9mCvQ9KYGzf8aFQvcOZs5eWj8j0iixJMO42bMsdYtj5E2WMcSe9smu_kWPa5-0LkCQ"
export const PWA_VAPID_PUBLIC_KEY_PROD = "BEk8sFSQun8m32kkK2l-Fy_GLH1GCHbdqenbE9N6lFj6G-EH2ZL3c_XO-5cVEOm8pfJSl8Q8d5m8GdbZQCSDCDY"